apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .ServiceName }}
  labels:
    app: {{ .ServiceName }}
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ .ServiceName }}
    spec:
      containers:
        - name: {{ .ServiceName }}
          image: docker.io/goforbroke1006/{{ .ServiceName }}:{{ .Release }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
#          livenessProbe:
#            httpGet:
#              path: /probe/health
#              port: 8080
#            initialDelaySeconds: 5
#            periodSeconds: 5
#          readinessProbe:
#            httpGet:
#              path: /probe/ready
#              port: 8080
#            initialDelaySeconds: 15
#            periodSeconds: 5
#            failureThreshold: 10
          resources:
            limits:
              cpu: 10m
              memory: 30Mi
            requests:
              cpu: 10m
              memory: 30Mi
      terminationGracePeriodSeconds: 30